# Generated by Django 2.2 on 2021-01-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(default='josh@gmail.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
