# Generated by Django 2.2 on 2021-01-10 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_agent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
